---
output:
  html_notebook:
    code_folding: show
    toc: yes
    toc_float: yes
  html_document:
    df_print: paged
    toc: yes
editor_options: 
  chunk_output_type: inline
---

# Wide to long
```{r}
long  <-  gather(merge, variable, measurement, 
                 Preis:Nachrichtenartikel, factor_key=TRUE)
```

# Drop one day only contained in google data
```{r}
long %>% 
  filter(date != "2018-02-06") ->
long
```

# Prepare special variable values (min, max, end, quartiles)
```{r}
mins <- group_by(long, variable) %>% slice(which.min(measurement)) # max value ts
maxs <- group_by(long, variable) %>% slice(which.max(measurement)) # min value ts
ends <- group_by(long, variable) %>% filter(date == max(date))  # last value of ts
quarts <- long %>% group_by(variable) %>% # quartiles for grey bar
  summarize(quart1 = quantile(measurement, 0.25, na.rm = TRUE),
            quart2 = quantile(measurement, 0.75, na.rm = TRUE)) %>%
  right_join(long)
```

# Create index values
```{r}
long %>% 
  filter(complete.cases(.), variable != "close_ratio") %>% 
  group_by(variable) %>% 
  mutate(max = max(measurement), index = measurement/max) %>% 
  filter(variable == "Preis" | variable == "Google-Suchen") ->
long.index

```

