---
title: "R Notebook"
output: html_notebook
---

# info
https://cran.r-project.org/web/packages/tmap/vignettes/tmap-nutshell.html

```{r}
require(pacman)
pacman::p_load(tmap,readr, tmaptools, ggmap, sp, broom, ggplot2, dplyr)

```

Set WD & Load Data
```{r}
wd <- "/Users/LR/Dropbox/DataVisualization/" # Lisa
setwd(wd)

# Load & prepare data -----------------------------------------------------
#price  <- read_csv("crypto-markets.csv")
#google <- read_csv("Bitcoin_google_1_10_2017.csv")
#news   <- read_csv("Bitcoin_news_1_10_2017.csv")

gg_0418_world <- read_csv("bitcoin_ggtrend_0418_world.csv", skip = 2)
colnames(gg_0418_world)[2] <- "Bitcoin_0418"
gg_0418_world2 <- read_csv("bitcoin_ggtrend_0418_world2.csv", skip = 2)
colnames(gg_0418_world2)[2] <- "Bitcoin_0418"


```



```{r}
world <- data(World)
world.shp <- sp::merge(World, gg_0418_world, by.x = "name", by.y = "Country", all.x = T)

# world.map <- get_map(world)
```

With TMap:
```{r}
tmap_mode("view")
(tm1 <- tm_shape(shp = world.shp) +
  tm_polygons("Bitcoin_0418", alpha = 0.5, 
              style = "pretty", interval.closure = "left") +
  tm_layout(legend.text.size = 0.8, legend.title.size = 1.1, frame = FALSE, 
            legend.outside = TRUE))

```

With GGplot
info: https://fcostartistician.wordpress.com/2017/09/13/how-to-deal-with-spatial-data-in-r-and-ggplot-shapefiles/
```{r}
data("World")
shapefile <- World
map <- shapefile
map@data$id_name <- seq(1,length(map@data$name))  #generate id

map_draw <- fortify(map, region = "id_name")
#Add the Map@data to the Map_draw data frame
map_draw$id <- as.numeric(map_draw$id)
data <- map@data
 
#Add the stats to the map data
map_draw <- left_join(map_draw, data, by = c('id'='id_name')) %>% 
      left_join(gg_0418_world, by = c("name" = "Country")) %>% 
      mutate(bitcoin = ifelse(is.na(Bitcoin_0418), 0, Bitcoin_0418))

# Just the map
ggmap +
  geom_polygon(data = map_draw,
               aes(long, lat, group = group), color = 'white',
               fill = 'grey') 

ditch_the_axes <- theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank()
)

ggmap +
     geom_polygon(data = map_draw,
                 mapping = aes(fill = bitcoin)) +
      #Add the scale of colour you want
     scale_fill_gradient()+
      ditch_the_axes+
      ggtitle("Add Title here")




```

